project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
      - text: "Hands on Exercise"
        menu:
          - text: "Hands on Exercise 1 : A Layered Grammar of Graphics: ggplot2 methods"
            href: HandsOnExercise/Hands_onExercise1/hands_onExercise1.html
          - text: "Hands on Exercise 2 : Beyond ggplot2 Fundamentals"
            href: HandsOnExercise/Hands_onExercise2/hands_onExercise2.html
          - text: "Hands-on Exercise 3.1: Interactive Data Visualisation"
            href: HandsOnExercise/Hands_onExercise3(1)/hands_onExercise3(1).html
          - text: "Hands-on Exercise 3.2: Animated Statistical Graphics"
            href: HandsOnExercise/Hands_onExercise3(2)/hands_onExercise3_2.html
          - text: "Hands on Exercise 4.1: Visualising Distribution"
            href: HandsOnExercise/Hands_onExercise4(1)/hands_onExercise4_1.html
          - text: "Hands on Exercise 4.2: Visual Statistical Analysis"
            href: HandsOnExercise/Hands_onExercise4(2)/hands_onExercise4_2.html
          - text: "Hands on Exercise 4.3: Visualising Uncertainty"
            href: HandsOnExercise/Hands_onExercise4(3)/hands_onExercise4_3.html
          - text: "Hands on Exercise 4.4: Building Funnel Plot with R"
            href: HandsOnExercise/Hands_onExercise4(4)/hands_onExercise4_4.html
          - text: "Hands on Exercise 5 : Modelling, Visualising and Analysing Network Data with R "
            href: HandsOnExercise/Hands_onExercise5/hands_onExercise5.html
      - text: "Take Home Exercises"
        menu:
          - text: " Take home Exercise 1 "
            href: TakehomeExercises/Take_homeExercise1/take_homeExercise1.html
          - text: " Take home Exercise 2 "
            href: TakehomeExercises/Take_homeExercise2/take_homeExercise2.html
      - text: "In Class Exercises"
        menu:
          - text: " In class Exercise 5 "
            href: InClassExercises/In_ClassExercise5/In_classExercise5.html
    right:
      - href: index.qmd
        text: Home
      - about.qmd
