project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
      - text: "Hands on Exercise"
        menu:
          - text: "Hands on Exercise 1"
            href: HandsOnExercise/Hands_onExercise1/hands_onExercise1.html
          - text: "Hands on Exercise 2"
            href: HandsOnExercise/Hands_onExercise2/hands_onExercise2.html
          - text: "Hands-on Exercise 3.1: Interactive Data Visualisation"
            href: HandsOnExercise/Hands_onExercise3(1)/hands_onExercise3(1).html
          - text: "Hands-on Exercise 3.2: Animated Statistical Graphics"
            href: HandsOnExercise/Hands_onExercise3(2)/hands_onExercise3(2).html
    right:
      - href: index.qmd
        text: Home
      - about.qmd
